### PR TITLE
Input styling

### PR DESCRIPTION
**Pull request by UdhbhavSinghRana**
Changed input-styling and made it from using absolute to using flex box and also changed color scheme in dark mode but in dark mode the shadow of input is having white color this should be changed to #1d243d but i am unable to do so, so please look into it :)

### CODE REVIEW

**Comment by TheTechRobo** [comment]
Thank you so much for this! The website looks a lot cleaner and the code is now much more maintainable.

Just one question - what do you mean by the shadow of the input in dark mode?

**Comment by UdhbhavSinghRana** [comment]
Screenshot from 2023-07-12 00-37-21
The white part that looks odd is the one I'm takling about. I have made a #form-contenu-dark i think you have to change the js for it to function and then just change background-image property to a more suitable color thank you.

**Comment by TheTechRobo** [comment]
@UdhbhavSinghRana I've fixed enabling dark mode for the form background. I have no idea what colours to use, do you have any ideas?

**Comment by UdhbhavSinghRana** [comment]
@TheTechRobo you can try using #0e1323

**Review by TheTechRobo — APPROVED** [review]

**Comment by TheTechRobo** [comment]
Thank you!

**Pull request merged**
