### PR TITLE
Refactor and Update Appearance

### PR DESCRIPTION
**Pull request by mattwright324**
- Rename `init.html` to `index.html`
- Rename gif to `loading.gif`
- Add and start using Skeleton as a very basic css library
    - http://getskeleton.com/
- Refactor inline `<style>`s and `<script>`s to files in the static folder
- Refactor dark mode to separate file and such that element styles are based on the `<html>` class instead of manually swapping classes for multiple elements
- API page has header linking back to finder page and has dark mode toggle

Preview (home)

image

Preview (api doc)

image

### CODE REVIEW

**Comment by TheTechRobo** [comment]
Thanks for the PR; this looks great!

One thing I'm immediately noticing is that in the HTML source code, the Jinja2 tags are no longer taking indentation into consideration. What I mean:

```diff
-             {% for logitem in logitems %}
-               <li>{{logitem}}</li>
-             {% endfor %}
+                {% for logitem in logitems %}
+                <li>{{logitem}}</li>
+                {% endfor %}
```

I've always found that indentation there (in the orange part), while it does make the generated HTML look a bit weird, makes the logic easier to follow (similar to how indentation in "real" code makes the logic easier to follow). Is there a specific reason why the consistent indentation is preferred?

**Comment by mattwright324** [comment]
I think its partially a side effect of the PyCharm HTML formatter as I didn't manually adjust indentation on the whole api page but also Jinja appears very similar to GitHub Page's Liquid for page templating and seems I used similar indentation for that too.

https://github.com/mattwright324/mattwright324.github.io/blob/master/index.html#L35-L76

Though I'm not really sure what the ideal formatting style for Jinja or Liquid templated pages should look like and can see your point for the original indentation style

**Comment by TheTechRobo** [comment]
I've added a .editorconfig to master, which should help, but I'm not sure I can make the Jinja2 contents indent. Can you merge/rebase and re-run the formatter? (The merge conflict is just newline vs no newline.) I can fix the Jinja2 indenting after it's merged if you don't want to.

This looks great! The .editorconfig should also help. I might add a contributing.md or something.

**Comment by mattwright324** [comment]
That editorconfig seems like it did something but didn't do everything, I did a PyCharm reformat and also a manual pass of indentation changes too. Which editor have you been using for this project?

**Comment by TheTechRobo** [comment]
I just use Vim because it's convenient.

What did the editorconfig not do? Just the Jinja2 or was there more?

**Comment by mattwright324** [comment]
Might be easier to show with a picture but it did indent some J2 but some sections J2+html were behind 1 or 2 indents. Formatter isn't changing anything after the manual adjustments so not sure the editor would have an effect

image

**Comment by TheTechRobo** [comment]
Alright thanks! Wish this was more straightforward lol. 

I'll merge when I'm back home.

**Review by TheTechRobo — APPROVED** [review]

**Pull request merged**
